### ISSUE TITLE
Twitter Errors

### ISSUE THREAD

**Issue by ScientiaEtVeritas** [strebo/strebo#1]
Fatal Error – Max Execution Time exceeded

UND

Notice: Undefined property: stdClass::$statuses in C:\xampp\htdocs\Strebo\SocialNetworks\Twitter.php on line 97

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\Strebo\SocialNetworks\Twitter.php on line 97

UND

Fatal Error – Operation times out after 0 ms with 0 out of 0 bytes received ...

**Comment by Aaper** [comment]
Hängt mit der Blockierung von Twitter zusammen, Max Execution Time ist eine Einstellung in der php.ini. Dort muss die max_execution_time von 30 (oder was auch immer dort eingestellt ist) auf 0 gesetzt werden.

**Comment by ScientiaEtVeritas** [comment]
Werden die Fehler / Warnungen nun abgefangen?
